import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/app/utils/lenis";

const comfortaa = Comfortaa({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Advokatloka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${comfortaa.className} h-full antialiased`}>
      <ReactLenis root>
        <body className="min-h-full flex flex-col">{children}</body>
      </ReactLenis>
    </html>
  );
}
